### ISSUE TITLE
Design Vale support Power

### ISSUE THREAD

**Issue by edelsohn** [edelsohn/vale#1]
https://github.com/project-everest/hacl-star/issues/454

https://github.com/project-everest/vale/pull/51

This is a proxy for the first part of the Vale Pull request for the design for Vale support for Power cryptographic instructions.

**Comment by mamonet** [comment]
Adding support of PowerPC architecture and implementing cryptography algorithms on HACL* are a work in progress and have big of milestone so far. ppc support integration with HACL* and SHA implementation are set in the next patch release after weekend.

**Comment by edelsohn** [comment]
Completed.
