### ISSUE TITLE
Implement SHA Hash for PowerPC

### ISSUE THREAD

**Issue by edelsohn** [edelsohn/vale#3]
Implementing SHA hash for PowerPC architecture in HACL* by adding the following modules:

module Vale.PPC64LE.InsSha
Vector SHA-256 Sigma instruction:
Vector SHA-256 Sigma Word

Code.Crypto.Sha.PPC64LE modules for SHA-256 function:
Update state
Digest calculation

**Comment by abcpro1** [comment]
Hello, I would like to signup to accomplish this task. I am assuming that a pull request would be submitted to this repository and you will be reviewing and merging it, am I correct?

**Comment by edelsohn** [comment]
Pull request created
https://github.com/project-everest/vale/pull/54

**Comment by edelsohn** [comment]
Updated pull request landed
https://github.com/hacl-star/hacl-star/pull/609
